spring.application.name=graphql-product
server.port=8080

# Cấu hình kết nối CSDL SQL Server (Hỗ trợ tiếng Việt Unicode)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GraphQL_ProductDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate JPA - Sử dụng NVARCHAR cho tất cả chuỗi tiếng Việt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_nationalized_character_data=true

# Cấu hình GraphiQL & GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.cors.allowed-origins=*
